// Copyright (C) Karim Agha - All Rights Reserved
// Unauthorized copying of this file, via any medium is strictly prohibited
// Proprietary and confidential. Authored by Karim Agha <karim@sentio.cloud>

 // This tells Catch to provide a main() - only do this in one cpp file
#define CATCH_CONFIG_MAIN 
#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS
#include "catch.h"

/**
 * This is the unit-tests entry point.
 * 
 * Please refer to the Catch2 documentation to learn more
 * about the autogenerated main() function and the structure
 * of unit tests modules.
 */